Disable email field in contact form
Plant-for-the-Planet-org/planet-donations pull request #403
Opened 2023-04-14 12:04 UTC by prachigarg19

When a user is logged in on the webapp and selects a project to donate to, they are able to edit the email that is within the contact details. This should not be possible, like it is not when you directly log in on donate.

2023-04-15 10:38 UTC, norbertschuler submitted a review, later dismissed
LGFM - tested with using token from planet-webapp->planet-donation as well as logging into planet-donation directly.

2023-04-18 04:23 UTC, mohitb35 requested changes

2023-04-18 04:23 UTC, mohitb35 commented on src/Donations/Components/ContactsForm.tsx
> +                  disabled={profile?.email.length !== 0}
This logic does not work for guest users. The email field is always disabled. 

For logged in/proxy-logged in users, there is a `profile` with an `email`, So the statement `profile?.email.length !== 0` evaluates to `true`.

For guest users, `profile` is `null`. So the statement `profile?.email.length !== 0` evaluates to `true`.

2023-05-09 04:29 UTC, mohitb35 approved these changes

2023-05-09 04:29 UTC, mohitb35 commented
LGTM

2023-05-09 06:18 UTC, merged