Enhance project details handling with classification and purpose variations
Plant-for-the-Planet-org/planet-donations pull request #470
Opened 2024-11-12 09:21 UTC by mohitb35

Introduce a utility for creating project details, improving the handling of project classifications and updating the GiftForm display logic based on project classification and frequency.

2024-11-18 09:35 UTC, mohitb35 commented on src/Utils/createProjectDetails.ts
> +  };
The response matches the `FetchProjectDetails` type, and code elsewhere in the project using this type handles the `FetchProjectDetails` type appropriately

2024-11-18 09:45 UTC, mohitb35 commented on src/Utils/createProjectDetails.ts
> +  }
It was structured this way to handle the discriminated union type of `FetchedProjects` which is extended by `PaymentOptions`. Taking the approach suggested here results in typescript warnings, as the type of `classification` differs for "trees" and "funds" projects.

2024-11-18 09:48 UTC, mohitb35 commented on src/Common/Types/QueryParamContextInterface.ts
> +  setGiftDetails: Dispatch<SetStateAction<GiftDetails | NoGift>>;
The SentGift type is used intentionally to describe the type expected while calling APIs. The GiftDetails type specifies the type of the value stored in context. While the types overlap, they are not the same.

2024-11-18 09:50 UTC, mohitb35 commented on public/locales/en/common.json
> +  "giftDedicatedTo": "This donation is dedicated to {{name}}",
This will be updated via Lingohub.

2024-11-18 09:53 UTC, mohitb35 commented on src/Donations/Micros/PaymentStatus/ThankyouMessage.tsx
> +    donation.gift.recipientEmail //TODOO - address TS warnings after /donations is updated to send gift data
Resolved in fb98cd9

2024-11-21 10:50 UTC, sunilsabatp approved these changes

2024-11-21 10:52 UTC, sunilsabatp commented
> Bug found: Currency selector seen in gift form for membership projects and other non-tree projects.
> 
> ![Screenshot 2024-11-19 at 4 51 30 PM](https://private-user-images.githubusercontent.com/44917347/387633155-a0d36b79-2fd8-4383-9cb4-7ec2f170cf5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxODY1MzcsIm5iZiI6MTczMjE4NjIzNywicGF0aCI6Ii80NDkxNzM0Ny8zODc2MzMxNTUtYTBkMzZiNzktMmZkOC00MzgzLTljYjQtN2VjMmYxNzBjZjVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDEwNTAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3MGIxZWRlZTc0MzM5NmFlYzdkMTgyMDI3MmJlNjk5YjRkYjBmNGNjMmU4MWY1NWY1ZTNhOGQzOTQzNzc3YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0wtGIASAgCSWAWidRIuSYt21MCl8qngszMVa7yX1FUc)

Are you planning to resolve this bug in this PR?

2024-11-21 13:13 UTC, mohitb35 commented
> > Bug found: Currency selector seen in gift form for membership projects and other non-tree projects.
> > ![Screenshot 2024-11-19 at 4 51 30 PM](https://private-user-images.githubusercontent.com/44917347/387633155-a0d36b79-2fd8-4383-9cb4-7ec2f170cf5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxODY1MzcsIm5iZiI6MTczMjE4NjIzNywicGF0aCI6Ii80NDkxNzM0Ny8zODc2MzMxNTUtYTBkMzZiNzktMmZkOC00MzgzLTljYjQtN2VjMmYxNzBjZjVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDEwNTAzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3MGIxZWRlZTc0MzM5NmFlYzdkMTgyMDI3MmJlNjk5YjRkYjBmNGNjMmU4MWY1NWY1ZTNhOGQzOTQzNzc3YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0wtGIASAgCSWAWidRIuSYt21MCl8qngszMVa7yX1FUc)
> 
> Are you planning to resolve this bug in this PR?

This is now resolved on bc4af28

2024-11-22 08:10 UTC, mariahosfeld requested changes
UI for recipient data is broken, below partial example, affects whole UI
![image](https://github.com/user-attachments/assets/ccc45408-37fa-4b76-8849-74a77c5f6dbc)

2024-11-22 10:37 UTC, mohitb35 commented on src/Common/InputTypes/MaterialTextField.tsx
>    },
The border was 0px earlier, and now it is removed. How is accessibility affected?

2024-11-22 10:48 UTC, mariahosfeld approved these changes
Functionality works, no longer issues with UI detected, but lets keep an eye out.

2024-12-03 10:19 UTC, merged