Allow PlanetCash payments for more types of donations
Plant-for-the-Planet-org/planet-donations pull request #471
Opened 2024-11-26 08:57 UTC by mohitb35

- Updates logic to display PlanetCash payment selector to allow more types of donations
- Extract logic for determining Planet Cash eligibility into a utility function, simplifying the DonationsForm component.
- Adds constants related to project purposes and classifications for better clarity.

2024-11-27 10:19 UTC, sunilsabatp approved these changes

2024-11-27 12:29 UTC, mariahosfeld reviewed
Functionality looks good.

2024-11-28 08:05 UTC, mariahosfeld requested changes
When the user is logged in, and has an active PlanetCash account, switching to a monthly schedule still shows the option "pay with PC", tested with project empowerment.

2024-11-28 12:51 UTC, mohitb35 commented
> When the user is logged in, and has an active PlanetCash account, switching to a monthly schedule still shows the option "pay with PC", tested with project empowerment.

Resolved in 2890661

2024-11-28 13:05 UTC, mariahosfeld reviewed
Issue with PlanetCash button for monthly donations has been resolved.

2024-12-03 09:42 UTC, sunilsabatp approved these changes

2024-12-03 09:45 UTC, mariahosfeld reviewed
Functionality looks good.

2024-12-03 09:46 UTC, merged